export enum UserRole {
  OPERATOR = 'OPERATOR',
  MANAGER = 'MANAGER',
  QUALITY_ASSURANCE = 'QUALITY_ASSURANCE',
  ADMIN = 'ADMIN',
}

export enum ApprovalState {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum AuditAction {
  CREATE = 'CREATE',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  VIEW = 'VIEW',
}